[book]
authors = [
    "Clément Guibout <clement.guibout@gmail.com>",
    "Arnaud Pascal <root@arnaud.sh>"
]
language = "fr"
multilingual = false
src = "src"
title = "CTF Writeups"
create-missing = false
[output.html.fold]
enable = true
[output.html]
git-repository-url = "https://github.com/salondesdevs/ctf-writeups"
mathjax-support = true

