[book]
authors = [
    "Clément Guibout <clement.guibout@gmail.com>",
    "Arnaud Pascal <root@arnaud.sh>"
]
language = "fr"
multilingual = false
src = "src"
title = "CTF Writeups"
create-missing = false

[output.html]
mathjax-support = true
